"""Persistent per-project git workspace.

Each project owns a real directory under ``workspaces_dir/<project>/``
that is initialised once and re-used across days. Finished milestones
become commits on a long-lived feature branch (``main`` for Phase 0;
Phase 4 may introduce branch-per-milestone).

All git work is done by shelling out to ``git`` via ``subprocess`` —
``pygit2`` is intentionally not a dependency (no native compile step,
trivial sandbox image).
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path


class GitError(RuntimeError):
    """Raised when a git command returns non-zero."""


@dataclass(frozen=True)
class CommitResult:
    """The hash of the commit that was just created and the message used."""

    commit_hash: str
    message: str


def _run_git(cwd: Path, *args: str) -> str:
    """Run ``git <args>`` in ``cwd`` and return stdout (stripped)."""
    proc = subprocess.run(  # noqa: S603,S607
        ["git", *args],
        cwd=cwd,
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise GitError(
            f"git {' '.join(args)} failed in {cwd}: "
            f"rc={proc.returncode} stderr={proc.stderr.strip()}"
        )
    return proc.stdout.strip()


class Workspace:
    """A single project's git working tree on disk."""

    def __init__(self, root: Path) -> None:
        self._root = root

    @property
    def root(self) -> Path:
        return self._root

    @property
    def git_dir(self) -> Path:
        return self._root / ".git"

    def exists(self) -> bool:
        return self.git_dir.is_dir()

    def init(self) -> None:
        """Initialise the workspace if it doesn't already exist.

        Idempotent: calling this on an already-initialised workspace is a
        no-op.
        """
        self._root.mkdir(parents=True, exist_ok=True)
        if self.exists():
            return
        _run_git(self._root, "init", "-b", "main")
        _run_git(self._root, "config", "user.email", "ai-dev-swarm@local")
        _run_git(self._root, "config", "user.name", "ai-dev-swarm")
        # Seed commit so HEAD exists.
        (self._root / "README.md").write_text(
            "# Generated by ai-dev-swarm\n", encoding="utf-8"
        )
        _run_git(self._root, "add", "README.md")
        _run_git(self._root, "commit", "-m", "chore: workspace bootstrap")

    def commit_all(self, message: str) -> CommitResult:
        """Stage every change and create one commit.

        Returns the commit hash. Raises :class:`GitError` if the working
        tree has nothing to commit — callers should use :meth:`is_dirty`
        first if a clean tree is expected.
        """
        _run_git(self._root, "add", "-A")
        _run_git(self._root, "commit", "-m", message)
        return CommitResult(
            commit_hash=_run_git(self._root, "rev-parse", "HEAD"),
            message=message,
        )

    def is_dirty(self) -> bool:
        """True when there are staged or unstaged changes."""
        status = _run_git(self._root, "status", "--porcelain")
        return bool(status)

    def head_commit(self) -> str:
        return _run_git(self._root, "rev-parse", "HEAD")

    def commit_count(self) -> int:
        out = _run_git(self._root, "rev-list", "--count", "HEAD")
        return int(out)


class WorkspaceManager:
    """Vends :class:`Workspace`s keyed by project name."""

    def __init__(self, root: Path) -> None:
        self._root = root
        self._root.mkdir(parents=True, exist_ok=True)

    def for_project(self, project_name: str) -> Workspace:
        """Return — initialising if needed — the workspace for ``project_name``."""
        safe = project_name.strip().replace("/", "_").replace(" ", "_")
        if not safe:
            raise ValueError("project_name must be non-empty")
        ws = Workspace(self._root / safe)
        ws.init()
        return ws
