"""Persistent per-project git workspace.

Each project owns a real directory under ``workspaces_dir/<project>/``
that is initialised once and re-used across days. Finished milestones
become commits on a long-lived feature branch (``main`` for Phase 0;
Phase 4 may introduce branch-per-milestone).

All git work is done by shelling out to ``git`` via ``subprocess`` —
``pygit2`` is intentionally not a dependency (no native compile step,
trivial sandbox image).
"""

from __future__ import annotations

import os
import stat
import subprocess
import tempfile
from collections.abc import Iterator
from contextlib import contextmanager, suppress
from dataclasses import dataclass
from pathlib import Path


class GitError(RuntimeError):
    """Raised when a git command returns non-zero."""


@dataclass(frozen=True)
class CommitResult:
    """The hash of the commit that was just created and the message used."""

    commit_hash: str
    message: str


def _run_git(cwd: Path, *args: str, env: dict[str, str] | None = None) -> str:
    """Run ``git <args>`` in ``cwd`` and return stdout (stripped)."""
    proc = subprocess.run(
        ["git", *args],
        cwd=cwd,
        check=False,
        capture_output=True,
        text=True,
        env=env,
    )
    if proc.returncode != 0:
        raise GitError(
            f"git {' '.join(args)} failed in {cwd}: "
            f"rc={proc.returncode} stderr={proc.stderr.strip()}"
        )
    return proc.stdout.strip()


@contextmanager
def _askpass_env(token: str) -> Iterator[dict[str, str]]:
    """Yield an env that feeds ``token`` to git as the HTTPS password.

    Writes a throwaway 0600 ``GIT_ASKPASS`` script that just echoes the
    token from the environment. The token never touches argv or
    ``.git/config``; the script body contains no secret. Both are torn
    down on exit.
    """
    fd, path = tempfile.mkstemp(prefix="aidevswarm-askpass-", suffix=".sh")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write('#!/bin/sh\nprintf %s "$AIDEVSWARM_GIT_TOKEN"\n')
        os.chmod(path, stat.S_IRWXU)  # 0700 — owner-only
        env = dict(os.environ)
        env["GIT_ASKPASS"] = path
        env["AIDEVSWARM_GIT_TOKEN"] = token
        env["GIT_TERMINAL_PROMPT"] = "0"
        yield env
    finally:
        with suppress(OSError):
            os.unlink(path)


_DEFAULT_AUTHOR_NAME = "ai-dev-swarm"
_DEFAULT_AUTHOR_EMAIL = "ai-dev-swarm@local"


class Workspace:
    """A single project's git working tree on disk."""

    def __init__(
        self,
        root: Path,
        *,
        author_name: str = _DEFAULT_AUTHOR_NAME,
        author_email: str = _DEFAULT_AUTHOR_EMAIL,
    ) -> None:
        self._root = root
        self._author_name = author_name
        self._author_email = author_email

    @property
    def root(self) -> Path:
        return self._root

    @property
    def git_dir(self) -> Path:
        return self._root / ".git"

    def exists(self) -> bool:
        return self.git_dir.is_dir()

    def init(self) -> None:
        """Initialise the workspace if it doesn't already exist.

        Idempotent. The git identity is (re)applied on every call — even
        for an already-initialised workspace — so a workspace created
        before the operator set their author identity picks it up on the
        next build instead of staying stuck with the old default.
        """
        self._root.mkdir(parents=True, exist_ok=True)
        if self.exists():
            self._configure_identity()
            return
        _run_git(self._root, "init", "-b", "main")
        self._configure_identity()
        # Seed commit so HEAD exists.
        (self._root / "README.md").write_text("# Generated by ai-dev-swarm\n", encoding="utf-8")
        _run_git(self._root, "add", "README.md")
        _run_git(self._root, "commit", "-m", "chore: workspace bootstrap")

    def _configure_identity(self) -> None:
        """Set ``user.name`` / ``user.email`` for this repo's commits."""
        _run_git(self._root, "config", "user.email", self._author_email)
        _run_git(self._root, "config", "user.name", self._author_name)

    def commit_all(self, message: str) -> CommitResult:
        """Stage every change and create one commit.

        Returns the commit hash. Raises :class:`GitError` if the working
        tree has nothing to commit — callers should use :meth:`is_dirty`
        first if a clean tree is expected.
        """
        _run_git(self._root, "add", "-A")
        _run_git(self._root, "commit", "-m", message)
        return CommitResult(
            commit_hash=_run_git(self._root, "rev-parse", "HEAD"),
            message=message,
        )

    def is_dirty(self) -> bool:
        """True when there are staged or unstaged changes."""
        status = _run_git(self._root, "status", "--porcelain")
        return bool(status)

    def head_commit(self) -> str:
        return _run_git(self._root, "rev-parse", "HEAD")

    def commit_count(self) -> int:
        out = _run_git(self._root, "rev-list", "--count", "HEAD")
        return int(out)

    # ------------------------------------------------------------------
    # Remote / push
    # ------------------------------------------------------------------

    def has_remote(self, name: str = "origin") -> bool:
        try:
            remotes = _run_git(self._root, "remote")
        except GitError:
            return False
        return name in remotes.split()

    def set_remote(self, url: str, *, name: str = "origin") -> None:
        """Point ``origin`` at ``url`` (idempotent).

        ``url`` must NOT contain a token — supply credentials at push
        time via :meth:`push`. We never persist a secret in
        ``.git/config``.
        """
        if self.has_remote(name):
            _run_git(self._root, "remote", "set-url", name, url)
        else:
            _run_git(self._root, "remote", "add", name, url)

    def push(self, branch: str = "main", *, token: str | None = None, name: str = "origin") -> None:
        """Push ``branch`` to ``origin``.

        When ``token`` is given, it is fed to git via a one-shot
        ``GIT_ASKPASS`` helper (the token lives only in this process's
        env + a 0600 temp script that echoes it), so it never appears in
        argv, ``.git/config``, or any error message.
        """
        if token:
            with _askpass_env(token) as env:
                _run_git(self._root, "push", "-u", name, branch, env=env)
        else:
            _run_git(self._root, "push", "-u", name, branch)


class WorkspaceManager:
    """Vends :class:`Workspace`s keyed by project name."""

    def __init__(
        self,
        root: Path,
        *,
        author_name: str = _DEFAULT_AUTHOR_NAME,
        author_email: str = _DEFAULT_AUTHOR_EMAIL,
    ) -> None:
        self._root = root
        self._root.mkdir(parents=True, exist_ok=True)
        self._author_name = author_name
        self._author_email = author_email

    def for_project(self, project_name: str) -> Workspace:
        """Return — initialising if needed — the workspace for ``project_name``."""
        safe = project_name.strip().replace("/", "_").replace(" ", "_")
        if not safe:
            raise ValueError("project_name must be non-empty")
        ws = Workspace(
            self._root / safe,
            author_name=self._author_name,
            author_email=self._author_email,
        )
        ws.init()
        return ws
