"""Router handling of operator-authored ``submit_idea``.

Queues a project directly (bypassing Scout / Ideator / Critic + novelty).
Refuses a duplicate in-flight name; non-destructive.
"""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from aidevswarm.orchestrator.command_router import CommandRouter
from aidevswarm.schemas import (
    Project,
    ProjectSpec,
    ProjectState,
    SubmitIdea,
)
from aidevswarm.tools.kill_switch import InMemoryKillSwitch
from tests.fakes import InMemoryProjectRepo


@dataclass
class _FakeSteering:
    def add_note(self, project_id: UUID, body: str, *, author: str = "human") -> int:
        return 1

    def pull_unconsumed(self, project_id: UUID, role: str) -> list[str]:
        return []


def _router() -> tuple[CommandRouter, InMemoryProjectRepo]:
    repo = InMemoryProjectRepo()
    router = CommandRouter(
        project_repo=repo,
        steering_repo=_FakeSteering(),
        kill_switch=InMemoryKillSwitch(),
    )
    return router, repo


def test_submit_idea_queues_a_project() -> None:
    router, repo = _router()
    res = router.dispatch(
        SubmitIdea(
            title="OpenAPI Spec Linter for Generated Stubs",
            summary="A CLI + library that validates OpenAPI 3.1 specs generated by codegen tools.",
            rationale="Codegen tools produce subtly invalid specs; this catches them in CI.",
            stack=["python", "typer"],
            tags=["openapi", "linter"],
        )
    )
    assert res.ok is True
    [created] = list(repo.rows.values())
    assert created.name == "openapi-spec-linter-for-generated-stubs"
    assert created.spec.title == "OpenAPI Spec Linter for Generated Stubs"
    assert created.spec.stack == ["python", "typer"]
    assert created.spec.score == 100  # operator-curated -> top score
    assert created.state is ProjectState.QUEUED


def test_submit_idea_falls_back_rationale_to_summary() -> None:
    router, repo = _router()
    res = router.dispatch(
        SubmitIdea(
            title="Tiny tool",
            summary="A tiny but useful CLI for some workflow.",
            # rationale left blank — should fall back to summary.
        )
    )
    assert res.ok is True
    [created] = list(repo.rows.values())
    assert created.spec.rationale == "A tiny but useful CLI for some workflow."


def test_submit_idea_refuses_duplicate_in_flight_name() -> None:
    router, repo = _router()
    repo.create(
        Project(
            name="open-api-spec-linter",
            spec=ProjectSpec(title="t", summary="s", rationale="r", stack=[], tags=[], score=85),
            state=ProjectState.BUILDING,
        )
    )
    res = router.dispatch(
        SubmitIdea(title="Open API Spec Linter", summary="duplicate slug for in-flight project.")
    )
    assert res.ok is False
    assert "already in flight" in res.detail


def test_submit_idea_allows_reuse_after_terminal() -> None:
    """A finished/killed project frees its name."""
    router, repo = _router()
    repo.create(
        Project(
            name="my-cool-tool",
            spec=ProjectSpec(title="t", summary="s", rationale="r", stack=[], tags=[], score=85),
            state=ProjectState.DONE,
        )
    )
    res = router.dispatch(
        SubmitIdea(title="My Cool Tool", summary="resubmit the same idea after the first shipped.")
    )
    assert res.ok is True
    assert len(repo.rows) == 2
